apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Values.projectName }}-code-storage"
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/{{ .Values.projectName }}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.projectName }}-code-claim"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi